# The default build environment is Ubuntu 12.04 (very old!) which doesn't
# support c++11, which we need for our bindings.  Instead, use the newer trusty
# (14.04) distribution.
sudo: required
dist: trusty

language: go
go:
  - "1.10.x"
  - "1.9"

# Indicate which versions of v8 to run the test suite against.
env:
  - V8_VERSION=6.3.292.48.1
  # Anything before 6.3 will break because of new ldflags definitions.
  # - V8_VERSION=6.2.414.42.1
  # - V8_VERSION=6.0.286.54.3

go_import_path: github.com/augustoroman/v8

# Need to download & compile v8 libraries before running the tests.
install: ./travis-install-linux.sh

notifications:
  email:
    on_failure: change
