package v8

// #include <stdlib.h>
// #include <string.h>
// #include "v8_c_bridge.h"
import (
	"C"
)

// Value kinds
const (
	KindUndefined                 = int32(C.kUndefined)
	KindNull                      = int32(C.kNull)
	KindNullOrUndefined           = int32(C.kNullOrUndefined)
	KindTrue                      = int32(C.kTrue)
	KindFalse                     = int32(C.kFalse)
	KindName                      = int32(C.kName)
	KindString                    = int32(C.kString)
	KindSymbol                    = int32(C.kSymbol)
	KindFunction                  = int32(C.kFunction)
	KindArray                     = int32(C.kArray)
	KindObject                    = int32(C.kObject)
	KindBoolean                   = int32(C.kBoolean)
	KindNumber                    = int32(C.kNumber)
	KindExternal                  = int32(C.kExternal)
	KindInt32                     = int32(C.kInt32)
	KindUint32                    = int32(C.kUint32)
	KindDate                      = int32(C.kDate)
	KindArgumentsObject           = int32(C.kArgumentsObject)
	KindBooleanObject             = int32(C.kBooleanObject)
	KindNumberObject              = int32(C.kNumberObject)
	KindStringObject              = int32(C.kStringObject)
	KindSymbolObject              = int32(C.kSymbolObject)
	KindNativeError               = int32(C.kNativeError)
	KindRegExp                    = int32(C.kRegExp)
	KindAsyncFunction             = int32(C.kAsyncFunction)
	KindGeneratorFunction         = int32(C.kGeneratorFunction)
	KindGeneratorObject           = int32(C.kGeneratorObject)
	KindPromise                   = int32(C.kPromise)
	KindMap                       = int32(C.kMap)
	KindSet                       = int32(C.kSet)
	KindMapIterator               = int32(C.kMapIterator)
	KindSetIterator               = int32(C.kSetIterator)
	KindWeakMap                   = int32(C.kWeakMap)
	KindWeakSet                   = int32(C.kWeakSet)
	KindArrayBuffer               = int32(C.kArrayBuffer)
	KindArrayBufferView           = int32(C.kArrayBufferView)
	KindTypedArray                = int32(C.kTypedArray)
	KindUint8Array                = int32(C.kUint8Array)
	KindUint8ClampedArray         = int32(C.kUint8ClampedArray)
	KindInt8Array                 = int32(C.kInt8Array)
	KindUint16Array               = int32(C.kUint16Array)
	KindInt16Array                = int32(C.kInt16Array)
	KindUint32Array               = int32(C.kUint32Array)
	KindInt32Array                = int32(C.kInt32Array)
	KindFloat32Array              = int32(C.kFloat32Array)
	KindFloat64Array              = int32(C.kFloat64Array)
	KindDataView                  = int32(C.kDataView)
	KindSharedArrayBuffer         = int32(C.kSharedArrayBuffer)
	KindProxy                     = int32(C.kProxy)
	KindWebAssemblyCompiledModule = int32(C.kWebAssemblyCompiledModule)
)
